coverage:
  status:
    project:
      default:
        target: 75%
    patch:
      default: yes
ignore:
  - build/*
  - *.bat
  - *.sh
  - tests/*
  - docs/*
  - assets/*
  - *.md
  - *.xml
comment:
  layout: "reach"
