name: Issue
description: Use this template to report a issue.
labels:
  - "Bug"
body:
  - type: markdown
    attributes:
      value: |-
        Thanks for reporting a Issue! Please fill the formulary below
        to create the issue and wait for a developer or Contributor to
        assist you. The time of this process is usually 72-120 hours.

  - type: checkboxes
    attributes:
      label: Confirmation
      description: Check before submitting.
      options:
        - label: "I'm aware that theres not already a open issue for this bug."
          required: true
        - label: "I'm using the latest release"
          required: false
        - label: "I'm aware that this is a issue caused by us and not a external project."
          required: true
        - label: "I'm aware that this is a real issue."
          required: true

  - type: dropdown
    attributes:
      label: Issue Type
      description: What kind of issue is this.
      options:
        - "Crash"
        - "Performance issues"
        - "Unexpected behaviour"
        - "Broken Features"
        - "Other (Describe)"
      multiple: false
    validations:
      required: true

  - type: textarea
    attributes:
      label: "# Steps to Reproduce"
      description: Describe step by step how to reproduce the bug
      placeholder: "N/A"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
      placeholder: "The feature should..."
    validations:
      required: true

  - type: input
    id: "logs"
    attributes:
      label: "Console / Logs URL"
      description: Paste a link to your logs (optional)
      placeholder: "https://paste.example.com/logs"
